// <auto-generated />
using System;
using FundFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FundFlowDbContext))]
    partial class FundFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FundFlow.Domain.Model.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Percentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("VersionId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("RequestId");

                    b.ToTable("ChangeLog", (string)null);
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EffectiveDateShifted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplacesRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RequestedFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultingVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SavingsPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("ReplacesRequestId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("ResultingVersionId")
                        .IsUnique();

                    b.HasIndex("SavingsPlanId");

                    b.ToTable("ChangeRequests");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeRequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("RequestId");

                    b.ToTable("ChangeRequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Instrument", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsinLikeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SavingsPlanEligible")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = "INS-01",
                            AssetClass = "Aktien-ETF",
                            IsinLikeId = "XXDEMO000011",
                            Name = "Demo Welt Aktien ETF",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-02",
                            AssetClass = "Aktien-ETF",
                            IsinLikeId = "XXDEMO000029",
                            Name = "Demo Europa Aktien ETF",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-03",
                            AssetClass = "Aktien-ETF",
                            IsinLikeId = "XXDEMO000037",
                            Name = "Demo Schwellenländer ETF",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-04",
                            AssetClass = "Rentenfonds",
                            IsinLikeId = "XXDEMO000045",
                            Name = "Demo Euro Staatsanleihen Fonds",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-05",
                            AssetClass = "Renten-ETF",
                            IsinLikeId = "XXDEMO000052",
                            Name = "Demo Unternehmensanleihen ETF",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-06",
                            AssetClass = "Mischfonds",
                            IsinLikeId = "XXDEMO000060",
                            Name = "Demo Mischfonds Ausgewogen",
                            SavingsPlanEligible = true
                        },
                        new
                        {
                            InstrumentId = "INS-07",
                            AssetClass = "Offener Immobilienfonds",
                            IsinLikeId = "XXDEMO000078",
                            Name = "Demo Immobilienfonds",
                            SavingsPlanEligible = false
                        });
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepotNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DemoSessionId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("SavingsPlans");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlanVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DemoSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiscarded")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SavingsPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoSessionId");

                    b.HasIndex("SavingsPlanId", "VersionNo")
                        .IsUnique();

                    b.ToTable("SavingsPlanVersions");
                });

            modelBuilder.Entity("FundFlow.Infrastructure.Sessions.DemoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DemoSessions", (string)null);
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Allocation", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.SavingsPlanVersion", null)
                        .WithMany("Allocations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeLogEntry", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.ChangeRequest", null)
                        .WithMany("ChangeLog")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeRequest", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.ChangeRequest", "ReplacesRequest")
                        .WithMany()
                        .HasForeignKey("ReplacesRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FundFlow.Domain.Model.SavingsPlanVersion", "ResultingVersion")
                        .WithOne("CreatedByRequest")
                        .HasForeignKey("FundFlow.Domain.Model.ChangeRequest", "ResultingVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.SavingsPlan", null)
                        .WithMany("ChangeRequests")
                        .HasForeignKey("SavingsPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacesRequest");

                    b.Navigation("ResultingVersion");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeRequestStatusHistory", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.ChangeRequest", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Customer", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Portfolio", b =>
                {
                    b.HasOne("FundFlow.Domain.Model.Customer", null)
                        .WithMany("Portfolios")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlan", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.Portfolio", null)
                        .WithMany("SavingsPlans")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlanVersion", b =>
                {
                    b.HasOne("FundFlow.Infrastructure.Sessions.DemoSession", null)
                        .WithMany()
                        .HasForeignKey("DemoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FundFlow.Domain.Model.SavingsPlan", null)
                        .WithMany("Versions")
                        .HasForeignKey("SavingsPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FundFlow.Domain.Model.ChangeRequest", b =>
                {
                    b.Navigation("ChangeLog");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Customer", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.Portfolio", b =>
                {
                    b.Navigation("SavingsPlans");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlan", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FundFlow.Domain.Model.SavingsPlanVersion", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("CreatedByRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
