<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FundFlow.Domain\FundFlow.Domain.csproj" />
    <ProjectReference Include="..\FundFlow.Infrastructure\FundFlow.Infrastructure.csproj" />
    <ProjectReference Include="..\FundFlow.Scenarios\FundFlow.Scenarios.csproj" />
  </ItemGroup>

</Project>
